#以下为配置环境的切换
spring:
  profiles:
    active: prod
---
spring:
  profiles: prod          #表示生产环境
#tomcat具体配置
server:
  port: 80
  servlet:
    context-path: /       #表示路径
---
spring:
  profiles: test          #表示测试环境
#tomcat具体配置
server:
  port: 81
  servlet:
    context-path: /
---
spring:
  profiles: asd
#tomcat具体配置
server:
  port: 8088
  servlet:
    context-path: /jt